import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export type ProjectKind = "node" | "flutter" | "mixed" | "unknown";

export interface ProjectDetection {
  kind: ProjectKind;
  testCommand: string | null;
  lintCommand: string | null;
  e2eCommand: string | null;
  hasGit: boolean;
  hasGh: boolean;
}

function hasBinary(name: string): boolean {
  return spawnSync("command", ["-v", name], { shell: "/bin/bash", stdio: "ignore" }).status === 0;
}

function nodeScripts(dir: string): Record<string, string> {
  try {
    const pkg = JSON.parse(readFileSync(join(dir, "package.json"), "utf8")) as { scripts?: Record<string, string> };
    return pkg.scripts ?? {};
  } catch {
    return {};
  }
}

export function detectProject(dir: string): ProjectDetection {
  const isNode = existsSync(join(dir, "package.json"));
  const isFlutter = existsSync(join(dir, "pubspec.yaml"));

  let kind: ProjectKind = "unknown";
  if (isNode && isFlutter) kind = "mixed";
  else if (isNode) kind = "node";
  else if (isFlutter) kind = "flutter";

  let testCommand: string | null = null;
  let lintCommand: string | null = null;
  let e2eCommand: string | null = null;

  if (isNode) {
    const scripts = nodeScripts(dir);
    if (scripts.test) testCommand = "npm test";
    if (scripts.lint) lintCommand = "npm run lint";
    if (scripts["test:e2e"]) e2eCommand = "npm run test:e2e";
    else if (scripts.e2e) e2eCommand = "npm run e2e";
  } else if (isFlutter) {
    testCommand = "flutter test";
    if (existsSync(join(dir, "integration_test"))) e2eCommand = "flutter test integration_test";
  }

  const hasGit = spawnSync("git", ["-C", dir, "rev-parse", "--is-inside-work-tree"], { stdio: "ignore" }).status === 0;

  return { kind, testCommand, lintCommand, e2eCommand, hasGit, hasGh: hasBinary("gh") };
}

function orTodo(value: string | null, todo: string): string {
  if (value) return value;
  return `echo 'TODO: set this command' # ${todo}`;
}

export function buildPipelineYaml(det: ProjectDetection): string {
  const lines: string[] = [];
  lines.push("name: feature-dev");
  lines.push(`# generated by 'claudeloop init' for a ${det.kind} project — edit freely`);
  lines.push("");
  lines.push("defaults:");
  lines.push("  permission_mode: bypassPermissions");
  lines.push("  wait_timeout_ms: 1800000");
  lines.push("");
  lines.push("stages:");

  lines.push("  - id: implement");
  lines.push("    type: agent");
  lines.push("    prompt: prompts/implement.md");
  lines.push("");

  lines.push("  - id: qa");
  lines.push("    type: agent");
  lines.push("    prompt: prompts/qa.md");
  lines.push("    until:");
  lines.push("      type: command");
  lines.push(`      run: "${orTodo(det.testCommand, "your test command")}"`);
  lines.push("    on_fail:");
  lines.push("      goto: implement");
  lines.push("      max_attempts: 5");
  lines.push("");

  if (det.hasGit && det.hasGh) {
    lines.push("  - id: draft-pr");
    lines.push("    type: command");
    lines.push('    run: "gh pr create --draft --fill || gh pr edit --add-label loop"');
    lines.push("");
  }

  lines.push("  - id: review");
  lines.push("    type: skill");
  lines.push("    skill: comprehensive-review:full-review");
  lines.push("    until:");
  lines.push("      type: pattern");
  lines.push('      success: "no (critical|high)"');
  lines.push("    on_fail:");
  lines.push("      fix: true");
  lines.push("      max_attempts: 10");
  lines.push("");

  lines.push("  - id: simplify");
  lines.push("    type: skill");
  lines.push("    skill: simplify");
  lines.push("");

  if (det.e2eCommand) {
    lines.push("  - id: e2e");
    lines.push("    type: agent");
    lines.push("    prompt: prompts/e2e.md");
    lines.push("    until:");
    lines.push("      type: command");
    lines.push(`      run: "${det.e2eCommand}"`);
    lines.push("    on_fail:");
    lines.push("      fix: true");
    lines.push("      max_attempts: 3");
    lines.push("");
  }

  if (det.hasGit && det.hasGh) {
    lines.push("  - id: merge");
    lines.push("    type: command");
    lines.push('    run: "gh pr merge --squash"');
    lines.push("    gate: human");
    lines.push("");
  }

  return lines.join("\n");
}

const IMPLEMENT_PROMPT = `You are implementing one actionable item in this repository.

Read the task from \`.claudeloop/task.md\`. Implement it following the conventions already
present in the codebase — match the surrounding style, naming, and structure.

Rules:
- Do NOT ask questions. If something is ambiguous, pick the most conventional option for
  this codebase and proceed. If truly blocked, write why to \`.claudeloop/blocked.md\` and stop.
- Make the smallest change that fully satisfies the task.
- Commit your work with a clear message when done.
`;

const QA_PROMPT = `You are the QA agent. Exercise the change that was just implemented the way a real user
would, then judge whether it actually works.

- Drive the product through the relevant flow with whatever tools fit this project
  (web → Playwright/Chrome, mobile → mobile-mcp, backend → HTTP/CLI).
- If behavior is wrong or incomplete, write concrete reproduction notes to
  \`.claudeloop/qa-feedback.md\` so the next implement pass can fix it.
- Do NOT ask questions. Report findings to the file and stop.

The pipeline runs the project's test command after you to decide pass/fail.
`;

const E2E_PROMPT = `Write or extend end-to-end tests covering the change just made, then make them pass.

- Put tests where this project keeps its e2e suite (match existing patterns).
- Cover the happy path plus the most likely failure the change could introduce.
- Do NOT weaken assertions to force a pass. If the feature is broken, fix the feature.
- Do NOT ask questions.
`;

const TASK_TEMPLATE = `# Task

Describe ONE actionable item here — what should change, and what "done" looks like from a
user's perspective. The implement stage reads this file.

Example:
> Add a \`/healthz\` endpoint to the backend that returns 200 with \`{"status":"ok"}\`.
`;

export interface ScaffoldResult {
  created: string[];
  skipped: string[];
}

function writeIfAbsent(path: string, content: string, result: ScaffoldResult): void {
  if (existsSync(path)) {
    result.skipped.push(path);
    return;
  }
  writeFileSync(path, content);
  result.created.push(path);
}

export function scaffold(dir: string, det: ProjectDetection): ScaffoldResult {
  const root = join(dir, ".claudeloop");
  const prompts = join(root, "prompts");
  mkdirSync(prompts, { recursive: true });

  const result: ScaffoldResult = { created: [], skipped: [] };
  writeIfAbsent(join(root, "pipeline.yaml"), buildPipelineYaml(det) + "\n", result);
  writeIfAbsent(join(prompts, "implement.md"), IMPLEMENT_PROMPT, result);
  writeIfAbsent(join(prompts, "qa.md"), QA_PROMPT, result);
  writeIfAbsent(join(prompts, "e2e.md"), E2E_PROMPT, result);
  writeIfAbsent(join(root, "task.md"), TASK_TEMPLATE, result);
  return result;
}
